Various sniffs: improve error messages
WordPress/WordPress-Coding-Standards pull request #2178
Opened 2022-12-21 14:56 UTC by jrfnl

### CodeAnalysis/EscapedNotTranslated: improvement to the error message

... to remove the presumption that positional parameters are being used.

### PHP/PregQuoteDelimiter: minor message tweak for clarity

### PHP/RestrictedPHPFunctions: minor message tweak for clarity

### PHP/TypeCasts: minor message tweak for clarity

... and remove the advise to assign `null` as this could cause yet other problems due to the PHP 8.1 "passing null to non-nullable" deprecation (though passing an unassigned variable is in a way just as bad, but that's a whole other story).

### Security/SafeRedirect: minor message tweak for clarity

2022-12-21 16:53 UTC, dingo-d approved these changes
Looks good to me, but I'm not a native speaker so I trust @GaryJones will be more thorough 😄

2022-12-22 09:56 UTC, GaryJones requested changes
Of the lines that have changed, I would suggest one extra change. The rest are 👍🏻 .

2022-12-22 09:56 UTC, GaryJones commented on WordPress/Sniffs/PHP/RestrictedPHPFunctionsSniff.php
> +				'message'   => '%s() is deprecated as of PHP 7.2 and removed in PHP 8.0, please use declared named or anonymous functions instead.',
```suggestion
				'message'   => '%s() is deprecated as of PHP 7.2 and removed in PHP 8.0. Please use declared named or anonymous functions instead.',
```

2022-12-22 10:32 UTC, jrfnl commented on WordPress/Sniffs/PHP/RestrictedPHPFunctionsSniff.php
> +				'message'   => '%s() is deprecated as of PHP 7.2 and removed in PHP 8.0, please use declared named or anonymous functions instead.',
Done!

2022-12-22 10:59 UTC, GaryJones approved these changes
✅

2022-12-22 10:59 UTC, merged